name: hr_app_ver2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.20.0  # Thêm Firebase Authentication
  cloud_firestore: ^4.13.6 # Thêm Firestore để lưu dữ liệu
  firebase_storage: ^11.6.7
  firebase_messaging: ^14.7.21
  firebase_auth_web: ^5.12.0 # Để Firebase tự chọn phiên bản phù hợp
  js: ^0.7.2 # Cho phép cập nhật phiên bản mới nhất của `js`
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  curved_navigation_bar: ^1.0.6
  sidebarx: ^0.17.1
  geolocator: ^12.0.0
  permission_handler: ^11.0.1
  excel: ^2.0.0-null-safety-3
  path_provider: ^2.1.1
  universal_html: ^2.2.4 # Dùng để tải file trên web  
  flutter_local_notifications: ^17.2.1
  animate_do: ^4.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
