// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Y6f7KCdi3cwP4NhTVTpqvhoUNKgo0ws',
    appId: '1:677761960214:web:9dee75bd54edee2fc3e837',
    messagingSenderId: '677761960214',
    projectId: 'hr-app-ver2',
    authDomain: 'hr-app-ver2.firebaseapp.com',
    storageBucket: 'hr-app-ver2.firebasestorage.app',
    measurementId: 'G-T94MQGC4HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNSxrOVigzxJ1GU6ZDKp0YE_EFBKNyqqw',
    appId: '1:677761960214:android:e77c07677846da2cc3e837',
    messagingSenderId: '677761960214',
    projectId: 'hr-app-ver2',
    storageBucket: 'hr-app-ver2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSvyW7UUPtkXstRQoUXnAi3ddyouTIwQ',
    appId: '1:677761960214:ios:04a0b597352d176ec3e837',
    messagingSenderId: '677761960214',
    projectId: 'hr-app-ver2',
    storageBucket: 'hr-app-ver2.firebasestorage.app',
    iosBundleId: 'com.example.hrAppVer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJSvyW7UUPtkXstRQoUXnAi3ddyouTIwQ',
    appId: '1:677761960214:ios:04a0b597352d176ec3e837',
    messagingSenderId: '677761960214',
    projectId: 'hr-app-ver2',
    storageBucket: 'hr-app-ver2.firebasestorage.app',
    iosBundleId: 'com.example.hrAppVer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Y6f7KCdi3cwP4NhTVTpqvhoUNKgo0ws',
    appId: '1:677761960214:web:de05ef1fd7e57b46c3e837',
    messagingSenderId: '677761960214',
    projectId: 'hr-app-ver2',
    authDomain: 'hr-app-ver2.firebaseapp.com',
    storageBucket: 'hr-app-ver2.firebasestorage.app',
    measurementId: 'G-WZN288XQEQ',
  );

}